// prgram block 
`include "environment.sv"

program test(intf intff);
environment env;

initial begin
     env = new(intff);

     // setting the number of transactions to be generated by the generator 
     env.g0.count = 30;

     env.run();
end

endprogram
